### ISSUE TITLE
jump-tag doesn't work

### ISSUE THREAD

**Issue by MKrbm** [harrisoncramer/jump-tag#2]
Hi there! I really love the concept of this plugin.

However, the plugin doesn't work fine.

when I hit command `:lua require("jump-tag").jumpPrevSibling()`  
it returns error.

![image](https://github.com/harrisoncramer/jump-tag/assets/57752203/cccd6ec6-b226-43dc-8d28-9f6b7fd829ff)

Thank you!

**Comment by harrisoncramer** [comment]
Thank you for reporting this issue!

This is an error in the `has_value` function, it looks like it's getting `nil` instead of a Lua table. However, I'm not able to replicate this issue.

Can you please provide replication instructions? For instance, drop an example file in this issue and tell me exactly where to position my cursor prior to attempting that jump? Thanks.

**Comment by mgax** [comment]
I can offer an example; admittedly, it's a Python file, arguably outside the scope of this package. The error shows up with the cursor anywhere in the file:

```py
def foo():
    print("bar")
```

**Comment by harrisoncramer** [comment]
Yeah this isn't meant to work for Python, only for HTML like languages. I'm closing this but please feel free to file another issue if someone can replicate.
